### ISSUE TITLE
Change CSS for display of all projects besides Calendar

### ISSUE THREAD

**Issue by ebeshero** [newtfire/Behrend75th#27]
Do this by changing `<div class="facsblock">` to `<div class="letterBlock">`

Then, create new CSS adapting the original Warren Letters CSS grid, which is simpler (doesn't have the extra space for notes:

```css
section[class="document"] {
 background-color:rgba(255, 255, 255, 0.4);
 border: thin solid maroon;
 display:grid;
 grid-auto-flow:column; 
 grid-template-columns:800px 400px; 
 grid-column-gap:20px;
}

section[class="document"] div.docImage {
background-color:rgba(255, 255, 255, 0.4);
display:grid;
grid-auto-flow:column;
grid-template-columns: 400px 400px /*minmax(auto, 400px)*/; 
/*  ebb: need to look up how minmax works.  */
grid-column-gap:20px;
}

section#fulltext {
    width:80%;
    margin:auto;
    display:grid;
    grid-auto-flow:row;
    grid-row-gap:50px;
}

div.docImage > figure > img {
 object-fit:contain;
 width:200%;
 margin-left: 50px;
 margin-top: 20px;
   
}

div.docImage > figure > figcaption {
 margin-left: 50px;
 margin-bottom: 10px;
 font-size: 16px;
}
```
